### ISSUE TITLE
Do you change the shape of the prediction result

### ISSUE THREAD

**Issue by Flyfoxs** [CyberZHG/keras-bert#10]
Thanks for your great work.
I see the original BERT prediction return 3 numpy, but you demo(load_and_predict.py) only return 2 numpy. Not sure if i'm misunderstand you or the original BERT.

**Comment by Flyfoxs** [comment]
I get conclusion(3 numpy) based on these 2 points. 
1)From this picture of this blog, I found it also output 3 array for some case.
https://plmsmile.github.io/2018/12/15/52-bert/
![image](https://user-images.githubusercontent.com/11268302/51013448-734d3800-159d-11e9-9fb1-e83ea6aa7efd.png)

2) from the end of this notebook,  I found the prediction get 3 numpy.
https://github.com/Separius/BERT-keras/blob/master/tutorial.ipynb
![image](https://user-images.githubusercontent.com/11268302/51013316-c5418e00-159c-11e9-8458-977ef911e76e.png)

**Comment by CyberZHG** [comment]
They're specific applications of the model. The outputs in this repo are the two tasks proposed in the paper.

**Comment by Flyfoxs** [comment]
Thanks for your patient, your repo help me easy to understand BERT.
