### ISSUE TITLE
Error while predicting using a saved model

### ISSUE THREAD

**Issue by devinharia** [CyberZHG/keras-bert#100]
I saved the model using model.save() and then loaded it back in a fresh instance. I used 'custom_objects=get_custom_objects()' as well while loading the model. 

Now when I am predicting, I get the following error -
'Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 3 arrays'

I did not get this error when I predicted after training the model. I see that if I remove the 'mask input' while predicting, I get back the original predictions, but ideally should not do so, any ideas why this might be happening?

**Comment by FlyCatZout** [comment]
the same question from devinharia, how to use the model i trained to predict in keras?

**Comment by FlyCatZout** [comment]
the same question from devinharia, how to use the model i trained to predict in keras?

**Comment by CyberZHG** [comment]
Could you provide minimal codes to reproduce the error?

**Comment by FlyCatZout** [comment]
> Could you provide minimal codes to reproduce the error?

 it is my problem that had been addressed, thanks a lot.

**Comment by hi-im-ryanli** [comment]
> > Could you provide minimal codes to reproduce the error?
> 
> it is my problem that had been addressed, thanks a lot.

Can you please provide a sample usage syntax of how to use the trained model?
