### ISSUE TITLE
out_put_layer_num=1是 最深的最后一层输出 还是第一层输出

### ISSUE THREAD

**Issue by taichuai** [CyberZHG/keras-bert#102]
您好，有两个问题：
1、调用模型时，out_put_layer_num=1是 最深的最后一层输出 还是第一层输出
2、设置可fine_tune时如　bert_model.layers[1].trainable = True，bert_layers[0] = 是bert的第一层输出还是最后一层输出
麻烦能解答一下，谢谢

**Comment by CyberZHG** [comment]
最后
