### ISSUE TITLE
 running tutorial from the project description, i only train NSP or masked LM too?

### ISSUE THREAD

**Issue by MNCTTY** [CyberZHG/keras-bert#109]
Hi! I have one question, may be I don't understand something
When I use example from this tutorial https://pypi.org/project/keras-bert/ , is the model only learns next sentence prediction task, or masked lm task too?

**Comment by CyberZHG** [comment]
Both

**Comment by CoSeCant-csc** [comment]
> Hi! I have one question, may be I don't understand something
> When I use example from this tutorial https://pypi.org/project/keras-bert/ , is the model only learns next sentence prediction task, or masked lm task too?

Hello, I ran the script of [https://github.com/CyberZHG/keras-bert#train--use](https://github.com/CyberZHG/keras-bert#train--use), raise error of "RuntimeError: You must compile your model before using it." 
Any suggestions ? thx

**Comment by CyberZHG** [comment]
@CoSeCant-csc I updated the document.

**Comment by CoSeCant-csc** [comment]
> @CoSeCant-csc I updated the document.

@CyberZHG  awesome ! thx very much

**Comment by MNCTTY** [comment]
> Both

hello, CyberZHG! thanks for your reply
I faced a problem that this script falls with an error 'resource exhausted' on first epoch train. I thought I must write a data batch generator, but then I saw that you already use it in the tutorial - from the library. So, maybe you have some ideas, what problem it may be? I have very vast resources on the machine I ran that code.

**Comment by MNCTTY** [comment]
omg, i found the problem, but it's crazy

Resource exhausted: OOM when allocating tensor with shape[1546,128,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
...

1546 from the shape - it is exactly total amount of pairs in my small dataset
why the algo from tutorial tries to pack them all in one huge tensor? there are even batch_generator in use... I totally don't understand

**Comment by CyberZHG** [comment]
@MNCTTY 
Because it generates a batch.

**Comment by MNCTTY** [comment]
@CyberZHG and how to generate much smaller batches using this tools?

**Comment by MNCTTY** [comment]
ok, i wrote a small batch generating function, and now this error is solved
but I still don't understand, why your tutorial generator() generates so huge batches

but! two new questions arised
if you have time, please, answer them

1. there is a code in the tutorial that creates a dictionary of tokens, based on inputed data. Why we need it? We have vocab file with much more amount of tokens. why we don't use it at all?

2. we need to do a tokenization of inputed data before training. but via which tokenizer? FullTokenizer from original google repository or Tokenizer from your module? why your version is better/more useful??
I see that it is based on vocabulary we build on inputed data. and I totally don't understand why we ignore original huge vocab now too.

**Comment by MNCTTY** [comment]
I noticed that `from keras_bert import extract_embeddings` doesnt' work:

> ImportError: cannot import name 'extract_embeddings' from 'keras_bert' (/usr/local/lib/python3.7/site-packages/keras_bert/__init__.py)

**Comment by CyberZHG** [comment]
> ok, i wrote a small batch generating function, and now this error is solved
> but I still don't understand, why your tutorial generator() generates so huge batches
> 
> but! two new questions arised
> if you have time, please, answer them
> 
> 1. there is a code in the tutorial that creates a dictionary of tokens, based on inputed data. Why we need it? We have vocab file with much more amount of tokens. why we don't use it at all?
> 2. we need to do a tokenization of inputed data before training. but via which tokenizer? FullTokenizer from original google repository or Tokenizer from your module? why your version is better/more useful??
>    I see that it is based on vocabulary we build on inputed data. and I totally don't understand why we ignore original huge vocab now too.

1. You don't have it when you try to train a new model.
2. It's the same, not better.

**Comment by CyberZHG** [comment]
> I noticed that `from keras_bert import extract_embeddings` doesnt' work:
> 
> > ImportError: cannot import name 'extract_embeddings' from 'keras_bert' (/usr/local/lib/python3.7/site-packages/keras_bert/**init**.py)

```bash
pip install --upgrade keras-bert
```

**Comment by MNCTTY** [comment]
hi @CyberZHG ! 
> 1. You don't have it when you try to train a new model.
ok, understand. and when I have pretrained model, I should use only its vocab? or mix its vocab and dict from inputed data?

> pip install --upgrade keras-bert
I like such simple solutions for me :)

**Comment by MNCTTY** [comment]
ok, I still hope that you'll answer

by the way, how to load this model after training from .hdf5 ? I understand that tutorial only speaks about load from .ckpt format
