### ISSUE TITLE
if reps is tensor.vector, you should specify the ndim

### ISSUE THREAD

**Issue by laibamehnaz** [CyberZHG/keras-bert#11]
I am trying to run the code  : 
from keras_bert import get_base_dict, get_model, gen_batch_inputs

# A toy input example
sentence_pairs = [
    [['all', 'work', 'and', 'no', 'play'], ['makes', 'jack', 'a', 'dull', 'boy']],
    [['from', 'the', 'day', 'forth'], ['my', 'arm', 'changed']],
    [['and', 'a', 'voice', 'echoed'], ['power', 'give', 'me', 'more', 'power']],
]

# Build token dictionary
token_dict = get_base_dict()  # A dict that contains some special tokens
for pairs in sentence_pairs:
    for token in pairs[0] + pairs[1]:
        if token not in token_dict:
            token_dict[token] = len(token_dict)
token_list = list(token_dict.keys())  # Used for selecting a random word

# Build & train the model
model = get_model(
    token_num=len(token_dict),
    head_num=5,
    transformer_num=12,
    embed_dim=25,
    feed_forward_dim=100,
    seq_len=20,
    pos_num=20,
    dropout_rate=0.05,
)
model.summary()

But it's showing me this error : 
ValueError                                Traceback (most recent call last)
<ipython-input-2-4bb86dab3b56> in <module>()
     28     seq_len=20,
     29     pos_num=20,
---> 30     dropout_rate=0.05,
     31 )
     32 model.summary()

~\Anaconda3\lib\keras_bert\bert.py in get_model(token_num, pos_num, seq_len, embed_dim, transformer_num, head_num, feed_forward_dim, dropout_rate, attention_activation, feed_forward_activation, custom_layers, training, lr)
     63         pos_num=pos_num,
     64         dropout_rate=dropout_rate,
---> 65         trainable=training,
     66     )
     67     transformed = embed_layer

~\Anaconda3\lib\keras_bert\layers\embedding.py in get_embedding(inputs, token_num, pos_num, embed_dim, dropout_rate, trainable)
     54         trainable=trainable,
     55         name='Embedding-Position',
---> 56     )(embed_layer)
     57     if dropout_rate > 0.0:
     58         dropout_layer = keras.layers.Dropout(

~\Anaconda3\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    455             # Actually call the layer,
    456             # collecting output(s), mask(s), and shape(s).
--> 457             output = self.call(inputs, **kwargs)
    458             output_mask = self.compute_mask(inputs, previous_mask)
    459 

~\Anaconda3\lib\keras_pos_embd\pos_embd.py in call(self, inputs, **kwargs)
    128         pos_embeddings = K.tile(
    129             K.expand_dims(self.embeddings[:seq_len, :self.output_dim], axis=0),
--> 130             K.stack([batch_size, 1, 1]),
    131         )
    132         if self.mode == self.MODE_ADD:

~\Anaconda3\lib\site-packages\keras\backend\theano_backend.py in tile(x, n)
   1067 
   1068 def tile(x, n):
-> 1069     y = T.tile(x, n)
   1070     if hasattr(x, '_keras_shape'):
   1071         if _is_explicit_shape(n):

~\Anaconda3\lib\site-packages\theano\tensor\basic.py in tile(x, reps, ndim)
   5413         elif ndim_check == 1:
   5414             if ndim is None:
-> 5415                 raise ValueError("if reps is tensor.vector, you should specify "
   5416                                  "the ndim")
   5417             else:

ValueError: if reps is tensor.vector, you should specify the ndim
Any help please

**Comment by CyberZHG** [comment]
`theano` backend is not supported :sweat:
