### ISSUE TITLE
TypeError: get_encoders() got an unexpected keyword argument 'use_adapter'

### ISSUE THREAD

**Issue by nwth** [CyberZHG/keras-bert#114]
get_model(token_num, pos_num, seq_len, embed_dim, transformer_num, head_num, feed_forward_dim, dropout_rate, attention_activation, feed_forward_activation, training, trainable, output_layer_num, use_adapter, adapter_units)
    115         # use_adapter=use_adapter,
    116         adapter_units=adapter_units,
--> 117         adapter_activation=gelu,
    118     )
    119     if training:
TypeError: get_encoders() got an unexpected keyword argument 'use_adapter'

hi,i always get this error when i run the demo code!
How to fix this ?

**Comment by CyberZHG** [comment]
```bash
pip install --upgrade keras-transformer
```

**Comment by nwth** [comment]
> ```shell
> pip install --upgrade keras-transformer
> ```

thank you！

**Comment by CoinCheung** [comment]
@CyberZHG Hi, would you please make it clear with which version of keras-bert could I avoid this error, it seems that the 0.80.0 still has the same error, and the newer version would require tensorflow2 as backend.

**Comment by apugachev** [comment]
Try `pip install keras-transformer==0.33.0`
