### ISSUE TITLE
TypeError: get_encoders() got an unexpected keyword argument 'use_adapter'

### ISSUE THREAD

**Issue by MNCTTY** [CyberZHG/keras-bert#116]
```
import os
from keras_bert import load_trained_model_from_checkpoint

layer_num = 12
checkpoint_path = 'rubert_cased_L-12_H-768_A-12_v1'

config_path = os.path.join(checkpoint_path, 'bert_config.json')
model_path = os.path.join(checkpoint_path, 'bert_model.ckpt')
model = load_trained_model_from_checkpoint(
    config_path,
    model_path,
    training=False,
    use_adapter=True,
    trainable=['Encoder-{}-MultiHeadSelfAttention-Adapter'.format(i + 1) for i in range(layer_num)] +
    ['Encoder-{}-FeedForward-Adapter'.format(i + 1) for i in range(layer_num)] +
    ['Encoder-{}-MultiHeadSelfAttention-Norm'.format(i + 1) for i in range(layer_num)] +
    ['Encoder-{}-FeedForward-Norm'.format(i + 1) for i in range(layer_num)],
)

```
I try to run this code from tutorial
and this error arises:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-a18dfbad0880> in <module>
     15     ['Encoder-{}-FeedForward-Adapter'.format(i + 1) for i in range(layer_num)] +
     16     ['Encoder-{}-MultiHeadSelfAttention-Norm'.format(i + 1) for i in range(layer_num)] +
---> 17     ['Encoder-{}-FeedForward-Norm'.format(i + 1) for i in range(layer_num)],
     18 )

TypeError: load_trained_model_from_checkpoint() got an unexpected keyword argument 'use_adapter'
```
By the way, i tried to upgrade keras-transformers - it didnt help

**Comment by CyberZHG** [comment]
```bash
pip install --upgrade keras-bert
```

**Comment by googlx** [comment]
这是keras-transformer版本问题，换成0.31.0就ok了

**Comment by MoreInterest** [comment]
> 这是keras-transformer版本问题，换成0.31.0就ok了

ok

**Comment by 1535966643** [comment]
> 这是keras-transformer版本问题，换成0.31.0就ok了

大哥牛逼

**Comment by CyberZHG** [comment]
This is an out-dated issue. See #190 and #191 if you still want to use the adapter.

**Comment by CyberZHG** [comment]
> 这是keras-transformer版本问题，换成0.31.0就ok了

Please read the last two lines carefully:

> TypeError: __*load_trained_model_from_checkpoint()*__ got an unexpected keyword argument 'use_adapter'
> By the way, i tried to upgrade keras-transformers - it didnt help

**Comment by 1535966643** [comment]
你好，可以使用的Bert模型都有哪些？albert,robert可以用吗

**Comment by 1535966643** [comment]
> > 这是keras-transformer版本问题，换成0.31.0就ok了
> 
> Please read the last two lines carefully:
> 
> > TypeError: **_load_trained_model_from_checkpoint()_** got an unexpected keyword argument 'use_adapter'
> > By the way, i tried to upgrade keras-transformers - it didnt help
你好，可以使用的Bert模型都有哪些？albert,robert可以用吗

**Comment by CoinCheung** [comment]
What is the solution to this problem ?? I am using 0.69.0 which still has the problem, do I need to down grade to 0.31.0?

**Comment by llpin1992** [comment]
pip install keras-bert==0.81.1 slove the problem

**Comment by Gavin4th** [comment]
大哥牛逼

**Comment by apugachev** [comment]
Try `pip install keras-transformer==0.33.0`
