### ISSUE TITLE
预训练模型保存

### ISSUE THREAD

**Issue by Xiao-da-1** [CyberZHG/keras-bert#118]
您好！我想请教一下，您给的例子里面“训练和使用”部分，没有直接保存预训练模型，而是使用了inputs 和output_layer，如果想要保存成Bert那种bert_model.ckpt、bert_config.json、vocab.txt可以吗？如果可以应该怎么做呢？麻烦您啦~

**Comment by CyberZHG** [comment]
不可以。要保存结果直接使用model.save、model.load，不需要强行转到tf的格式。

**Comment by Xiao-da-1** [comment]
> 不可以。要保存结果直接使用model.save、model.load，不需要强行转到tf的格式。

好的！但是我用model.save()后又出现一个问题，就是在载入模型后，做：
indices, segments = tokenizer.encode(first, second)
indices_data = indices_data.append(indices)
segments_data = segments_data.append(segments)
pred = pretrain_model.predict([indices_data,segments_data])
用自己预训练的模型获得预测结果，会报错：
ValueError: Error when checking model input: you are passing a list as input to your model, but the model expects a list of 3 Numpy arrays instead. The list you passed was: [None, None]
您知道哪里出错了吗？谢谢！

**Comment by CyberZHG** [comment]
append返回值为None；应该使用`training=False`的模型。
