### ISSUE TITLE
How to use Bert in keras Embedding layer?

### ISSUE THREAD

**Issue by rnnnnn** [CyberZHG/keras-bert#12]
Hi, 

I find embedding.py
https://github.com/CyberZHG/keras-bert/blob/master/keras_bert/layers/embedding.py

but how can i add it into my Keras model, and how i input data to pretrain bert embedding?

Keras model is:

model = Sequential()
model.add(TokenEmbedding)
model.add(Bidirectional(LSTM(256, return_sequences=True)))
model.add(Dropout(0.5))
model.add(TimeDistributed(Dense(len(tag2index))))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.001),metrics=['accuracy'])

is error, the error message is :
TypeError: The added layer must be an instance of class Layer. Found: <class '__main__.TokenEmbedding'>

**Comment by elsheikh21** [comment]
Did you figure it out yet? @rnnnnn

**Comment by elsheikh21** [comment]
for future readers [read this stackoverflow question](https://stackoverflow.com/questions/58607787/bert-embedding-layer-raises-type-error-unsupported-operand-types-for-non)
