### ISSUE TITLE
How to get sequence output from bert model when training = True

### ISSUE THREAD

**Issue by ananya0112** [CyberZHG/keras-bert#121]
How to get sequence output when `training=True`, is it accurate to use  `bert.get_layer("Encoder-12-FeedForward-Norm").output`?

Kindly help - Thanks!

**Comment by CyberZHG** [comment]
Correct. Remember to use `bert.inputs[:2]` if you don't need the MLM output.

**Comment by ananya0112** [comment]
Thank you for the clarification.
