### ISSUE TITLE
AttributeError: 'Dense' object has no attribute 'outbound_nodes'

### ISSUE THREAD

**Issue by Xiaoping777** [CyberZHG/keras-bert#123]
**Describe the Bug**

when run "outputs = keras.layers.Dense(units=2, activation='softmax')(dense)"
got error : AttributeError: 'Dense' object has no attribute 'outbound_nodes'

**Version Info**

* [X] I'm using the latest version

**Minimal Codes To Reproduce**

```python
import keras_bert

inputs = model.inputs[:2]
dense = model.get_layer('NSP-Dense').output
outputs = keras.layers.Dense(units=2, activation='softmax')(dense)

pass
```

**Comment by CyberZHG** [comment]
I'm not able to reproduce the error.

**Comment by Dimesio** [comment]
`s, input_tensors, output_tensors, arguments)
   1740         # For compatibility with external Keras, we use the deprecated
   1741         # accessor here.
-> 1742         layer.outbound_nodes.append(self)
   1743     # For compatibility with external Keras, we use the deprecated
   1744     # accessor here.

AttributeError: 'Dense' object has no attribute 'outbound_nodes'`

I get the same error, installed this today from pip

**Comment by CyberZHG** [comment]
@Dimesio 

The TPU classification demo uses the same mechanism and runs without error.
Could you paste your codes that lead to this error?

https://colab.research.google.com/github/CyberZHG/keras-bert/blob/master/demo/tune/keras_bert_classification_tpu.ipynb

![image](https://user-images.githubusercontent.com/853842/63412796-018a7600-c42b-11e9-8c8b-bdde4de53c57.png)

**Comment by Dimesio** [comment]
I'm form fitting it to use in a gpu scope, so I took out the code for the strategy. I was under the impression that the strategy parts were only for TPU?
Here is the code changed:

```
pretrained_path = './models/uncased_L-12_H-768_A-12'
config_path = os.path.join(pretrained_path, 'bert_config.json')
checkpoint_path = os.path.join(pretrained_path, 'bert_model.ckpt')
vocab_path = os.path.join(pretrained_path, 'vocab.txt')

#os.environ['TF_KERAS'] = '1'


token_dict = {}
with codecs.open(vocab_path, 'r', 'utf8') as reader:
    for line in reader:
        token = line.strip()
        token_dict[token] = len(token_dict)

model = load_trained_model_from_checkpoint(
    config_path,
    checkpoint_path,
    training=True,
    trainable=True,
    seq_len=SEQ_LEN,
    )

dataset = tf.keras.utils.get_file(
    fname="aclImdb.tar.gz", 
    origin="http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz", 
    extract=True,
    )

tokenizer = Tokenizer(token_dict)


**load tranx/y etc...

inputs = model.inputs[:2]
dense = model.get_layer('NSP-Dense').output
outputs = keras.layers.Dense(units=2, activation='softmax')(dense)

model = keras.models.Model(inputs, outputs)
model.compile(
    RAdam(lr=LR),
    loss='sparse_categorical_crossentropy',
    metrics=['sparse_categorical_accuracy'])
```

**Comment by CyberZHG** [comment]
@Dimesio 

It's supposed to be working in all environments.
I'm not able to reproduce the error with your codes either.

**Comment by CyberZHG** [comment]
Possible cause:

* You're using `tensorflow==1.13.2`
* `from tensorflow.python import keras`
* `TF_KERAS=1` is not set properly

**Comment by Dimesio** [comment]
So the colab notebook worked fine with `from tensorflow.python import keras` and building the model using the strategy, but for GPU/CPU you were on the dot with replacing that with `import keras` instead. Thanks for the help!

**Comment by Xiaoping777** [comment]
actually, after I re-started the PC, the error message is disappear. 

As the final output is binary, I've changed the output activation function='sigmoid' and 
model.compile(
    AdamWarmup(decay_steps=decay_steps, warmup_steps=warmup_steps, lr=LR),
    **loss="binary_crossentropy"**, #'sparse_categorical_crossentropy',
    **metrics=['acc']**, #['sparse_categorical_accuracy'],
)
it works ok so far.

also I cannot run it in TPU environment, I directly ran it on CPU with batch_sized = 16, 

I changed the code as below:

'''
tpu_address = 'grpc://' + os.environ['COLAB_TPU_ADDR']
strategy = tf.contrib.tpu.TPUDistributionStrategy(
    tf.contrib.cluster_resolver.TPUClusterResolver(tpu=tpu_address)
)

with tf.keras.utils.custom_object_scope(get_custom_objects()):
    tpu_model = tf.contrib.tpu.keras_to_tpu_model(model, strategy=strategy)
    
with tf.keras.utils.custom_object_scope(get_custom_objects()):
    tpu_model.fit(
        train_x,
        train_y,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
    )
'''
    
history = model.fit(
        train_x,
        train_y,
        epochs=EPOCHS,
        validation_data=(test_x, test_y),
        batch_size=BATCH_SIZE
    )

It runs slowly, I will report back when the results is available

**Comment by CyberZHG** [comment]
@Dimesio 

That is because one can only use `tf.keras` on TPU. Just use `import keras` and ignore `TF_KERAS` if you don't know much about `tf.keras`.
