### ISSUE TITLE
关于gelu实现的差异

### ISSUE THREAD

**Issue by bojone** [CyberZHG/keras-bert#129]
我发现你的实现之中，如果用tensorflow后端的话，gelu激活函数是用tf自带的erf函数实现的，但是我看了官方bert的源码，是通过tanh来近似的：https://github.com/google-research/bert/blob/master/modeling.py#L264

我也比较过两者的差异，发现它们的输出会在小数点后第二三位开始出现差异，所以我想请教一下这个问题，究竟使用哪个版本好？

**Comment by CyberZHG** [comment]
实际上官方代码早期版本用的是erf，后来才改成近似计算。

**Comment by CyberZHG** [comment]
https://github.com/google-research/bert/commit/bee6030e31e42a9394ac567da170a89a98d2062f

**Comment by bojone** [comment]
我比较关心的是哪个预训练权重对应哪个版本的gelu（捂脸）

**Comment by CyberZHG** [comment]
😹 最早公布的那批用的肯定是精确计算

**Comment by bojone** [comment]
感觉这改动对强迫症患者真难受啊...
