### ISSUE TITLE
padding对结果的影响

### ISSUE THREAD

**Issue by bojone** [CyberZHG/keras-bert#130]
这两天我自己也实现了一个bert4keras（ https://github.com/bojone/bert4keras ），参考了不少大佬的源码，在此先感谢一下。

在测试之中我意外发现一个小问题，这个问题在你我的实现中都存在，就是序列padding的0的数目会轻微影响序列的输出结果，也就是说[1, 2, 3, 0, 0]跟[1, 2, 3, 0, 0, 0, 0, 0]经过encode后，前几项都是有差别的，差别在1e-5左右。

这问题也不大，只是好奇这个差别的来源，毕竟理论上padding的效应已经被mask掉了

**Comment by CyberZHG** [comment]
因为tf的数值计算不稳定：

```python
import tensorflow as tf

tf.enable_eager_execution()

src = [0.7377831935882568, 0.7854524850845337, 1.0, 0.7377831935882568, 0.0]

a = tf.convert_to_tensor(src)
b = tf.convert_to_tensor(src + [0.0] * 5)

print(tf.reduce_sum(a).numpy().tolist(), tf.reduce_sum(b).numpy().tolist())
```
