### ISSUE TITLE
Minor issue in demo

### ISSUE THREAD

**Issue by michael-aloys** [CyberZHG/keras-bert#14]
Hi,

in https://github.com/CyberZHG/keras-bert/blob/master/demo/load_model/load_and_extract.py#L28

the sequence input is encoded as

`seg_input = np.asarray([[0] * len(tokens) + [0] * (512 - len(tokens))])`

I think the second part should be [1], i.e.

`seg_input = np.asarray([[0] * len(tokens) + [1] * (512 - len(tokens))])`

Only then is the padding part masked correctly. For the demo it does not make any difference directly as only the len(tokens) tokens are checked. But when this is used as a basis for something more complex, this might create a problem.

**Comment by CyberZHG** [comment]
The second part does not involoved in the calculation of attentions.
