### ISSUE TITLE
Load model error,  .h5 file load error: error message = 'Is a directory'

### ISSUE THREAD

**Issue by luzhongqiu** [CyberZHG/keras-bert#141]
I made a classification task, I save the model(also tried save weights), but I can not load the .h5 file, error message are below

OSError: Unable to open file (file read failed: time = Tue Sep 24 16:30:59 2019
, filename = '/root/.keras/datasets/chinese_L-12_H-768_A-12', file descriptor = 25, errno = 21, error message = 'Is a directory', buf = 0x7ffdc8a0ade0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)

It seem that when i use `keras.models.load_model`, it read a folder.

```python
layer_num = 12
bert_model = load_trained_model_from_checkpoint(
    paths.config,
    paths.checkpoint,
    seq_len=512,
    training=False,
    use_adapter=True,
    trainable=['Encoder-{}-MultiHeadSelfAttention-Adapter'.format(i + 1) for i in range(layer_num)] +
    ['Encoder-{}-FeedForward-Adapter'.format(i + 1) for i in range(layer_num)] +
    ['Encoder-{}-MultiHeadSelfAttention-Norm'.format(i + 1) for i in range(layer_num)] +
    ['Encoder-{}-FeedForward-Norm'.format(i + 1) for i in range(layer_num)],
)

model_input = bert_model.inputs
x = keras.layers.Lambda(lambda x: x[:, 0])(bert_model.outputs[0])
p = keras.layers.Dense(1, activation='sigmoid')(x)
model = keras.Model(model_input, p)
model.compile(
    loss='binary_crossentropy',
    optimizer=optimizers.Adam(1e-5),
    metrics=[metrics.binary_accuracy]
)

```

**Comment by luzhongqiu** [comment]
sorry , I have something mistake in my code

**Comment by kevinlinxc** [comment]
@luzhongqiu what was the mistake in your code? I have the same issue

**Comment by tamaralipows** [comment]
@kevinlinxc Have you figured out this issue?

**Comment by kevinlinxc** [comment]
@tamaralipows I think the issue was that in my training, I used save_model("name") instead of of save_model("name.h5"). Without the h5, it created a folder that contained some files, whereas with the .h5, it creates a single file that you can use with load_model. Using different versions of Keras while training and testing was also a problem so try avoiding that.
