### ISSUE TITLE
keras.utils.multi_gpu_model() does not work

### ISSUE THREAD

**Issue by superxuxin** [CyberZHG/keras-bert#142]
Running the following code

model = load_trained_model_from_checkpoint(config_path, checkpoint_path, seq_len=10, training=True)
model = keras.utils.multi_gpu_model(model, 2)
model.summary(line_length=120)

I got a strange model that only contains very few layers. Commenting out the multi_gpu_model() part give me the expected model. Does anyone see a similar issue?

**Comment by CyberZHG** [comment]
It's the expected behavior.

**Comment by superxuxin** [comment]
@CyberZHG Could you elaborate on why this is the expected behavior? I thought multi_gpu_model() would duplicate the model on multiple gpus and each model should be identical to the single gpu model? How to use the muti-gpu model in a classification task (i.e. there is no 'NSP-Dense' layer)? Still learning keras/bert, so thank you so much for your patience.
