### ISSUE TITLE
Retraining vs. training from scratch inconsistency?

### ISSUE THREAD

**Issue by UriLawgeex** [CyberZHG/keras-bert#16]
Hello, thanks for your effort and work in this project. I attempt to train two models using the same data and generator code (based on gen_batch_inputs in bert.py), once using get_model and the other using load_model_from_checkpoint. As an aside, I am still unsure whether the second option is ok: your readme states that "Official pre-trained models could be loaded for feature extraction and prediction" but in Issue #1 you seem to say that the official models cannot be loaded correctly with this implementation. 
In any case, when using get_model training proceeds as expected, but when using load_model_from_checkpoint, I get:
`ValueError: Error when checking target: expected MLM to have shape (512, 30522) but got array with shape (512,1)`
(30522 is the length of my token_list / size of my token_dict)
Am I missing an obvious reason for this, or is this a problem with the code?

**Comment by CyberZHG** [comment]
I wasn't planning to write codes for loading official model when replying to #1.

**Comment by CyberZHG** [comment]
I don't know what causes your case since `MLM` layer has no weights.

**Comment by UriLawgeex** [comment]
I see that gen_batch_inputs in bert.py adds mlm output as a single number: `line 185: mlm_output.append(token_dict.get(token, unknown_index))`
but the MLM layer itself outputs a one-hot encoding: `expected MLM to have shape (512, 30522)`
(that is also the shape I see if I call `model.get_layer('MLM').output_shape`). I would deduce from this that there is a problem in gen_batch_inputs, but I don't understand why the training process _does_ work when initializing a new model. Any ideas?

**Comment by CyberZHG** [comment]
The model uses sparse cross-entropy loss, you don't need to expand the dimensions of the output.

https://github.com/CyberZHG/keras-bert/blob/5647a8917d340d44d90b952be682678ba33d33a7/keras_bert/bert.py#L108

**Comment by UriLawgeex** [comment]
Ah, that's it! get_model uses sparse cross-entropy loss, but load_trained_model_from_checkpoint uses MSE:
loader.py, l. 41: `model.compile(optimizer='adam', loss='mse', metrics={})`. Can you change this?
