### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by linWujl** [CyberZHG/keras-bert#162]
Hi, when i use the model to fine-tune a classification task, get the following error:
AttributeError: 'tuple' object has no attribute 'layer'.  code as:
model = load_trained_model_from_checkpoint(
    config_path,
    checkpoint_path,
    training=True,
    trainable=True,
    seq_len=SEQ_LEN,
)
inputs = model.inputs[:2]
dense = model.get_layer('NSP-Dense').output
outputs = keras.layers.Dense(units=2, activation='softmax')(dense)

model = keras.models.Model(inputs, outputs)
model.compile(
    RAdam(lr=LR),
    loss='sparse_categorical_crossentropy',
    metrics=['sparse_categorical_accuracy'],
)
How can i fit this problem, thanks a lot!

**Comment by karimmahalian** [comment]
Hi,

How did u solve the problem? I am facing the same issue 

thanks in advance

**Comment by kk-fan** [comment]
Hi,

How did u solve the problem? I am facing the same issue

thanks in advance

**Comment by kk-fan** [comment]
i solved it， Add TF_KERAS=1 to environment variables to use tensorflow.python.keras.
see [keras-bert 0.89.0](https://pypi.org/project/keras-bert/)
