### ISSUE TITLE
Run extract_embeddings with GPU

### ISSUE THREAD

**Issue by 336655asd** [CyberZHG/keras-bert#170]
How can I run **extract_embeddings** with GPU? It takes a lot of time when I extract embeddings from a large corpus. And I found GPU-Util is 0 which may imply that the default settings is no-GPU.

**Comment by yyccR** [comment]
how to run extract_embeddings with GPU，I found it too slow runs on cpu

**Comment by mathshangw** [comment]
excuse me did you solve it
