### ISSUE TITLE
fine-tuning

### ISSUE THREAD

**Issue by OKtang** [CyberZHG/keras-bert#173]
你好，
请问在做分类任务的时候必须将training设置为True，获取NSP层嘛？可以将training设置为False，然后获取模型输出的第一维嘛？

**Comment by FanYaning** [comment]
不必须为training=True。
当设置training=False，keras-bert默认返回最后一个transformer的输出；此种用法类似[bert-as-service](https://github.com/hanxiao/bert-as-service)提取句子的特征向量，作为下游层的输入。
当设置training=False，在训练样本时，bert模型层的权值是不更新的，只会更新下游层的权值；如果你需要bert模型层也跟着训练一起更新权值，可通过配置trainable，指定需要更新权值的层的前缀名，就可。

具体可研究load_trained_model_from_checkpoint方法实现。

**Comment by 1535966643** [comment]
你好，在fintune的时候，bert接了其他的网络，那我怎么做mask呢
