### ISSUE TITLE
Building custom model over the final embedding layer

### ISSUE THREAD

**Issue by njordsir** [CyberZHG/keras-bert#19]
BERT supposedly generates 768 dimensional embeddings for tokens. I am trying to build a multi-class classification model on top of this. My assumption is that the output of layer `Encoder-12-FeedForward-Norm` of shape `(None, [seq_length], 768)` would give this embeddings. This is what I am trying :

```
model = load_trained_model_from_checkpoint(config_path, checkpoint_path, training=True, seq_len=seq_len)

new_out = Bidirectional(LSTM(50, return_sequences=True, 
                       dropout=0.1, 
                       recurrent_dropout=0.1))(model.layers[-9].output)
new_out = GlobalMaxPool1D()(new_out)
new_out = Dense(50, activation='relu')(new_out)
new_out = Dropout(0.1)(new_out)
new_out = Dense(6, activation='sigmoid')(new_out)

newModel = Model(model.inputs[:2], new_out)
```
I get the following error for `new_out = GlobalMaxPool1D()(new_out)` : 
```
TypeError: Layer global_max_pooling1d_11 does not support masking, but was passed an input_mask: Tensor("Encoder-12-FeedForward-Add/All:0", shape=(?, 128), dtype=bool)
```
I am not sure how masking is involved if I am just using the output of the encoder.

The paper mentions that the output corresponding to just the first `[CLS]` token should be used for classification. On trying this : 
```
new_out = Lambda(lambda x: x[:,0,:])(model.layers[-9].output)
```
the model trains (although with poor results).

How can the pre-loaded model be used for classification?

**Comment by BerenLuthien** [comment]
It looks that the author provided a demo: 
`
inputs, output_layer = get_model(  # `output_layer` is the last feature extraction layer (the last transformer)
...
    training=False,  # The input layers and output layer will be returned if `training` is `False`
)
`
Then Any classifier can be added on top of this `embeds`, such as LSTM or Logistic Regression.

**Comment by CyberZHG** [comment]
#7 Sentence Embedding

`GlobalMaxPool1D` doesn't support masking. Following is a modification that suits this case: 

https://github.com/CyberZHG/keras-bert/blob/02c7eb20c56b02ed74226d056354658c247ab52c/keras_bert/layers/pooling.py#L5-L21

I've also add a demo for sentence embedding with pooling:

https://github.com/CyberZHG/keras-bert/blob/02c7eb20c56b02ed74226d056354658c247ab52c/demo/load_model/load_and_pool.py#L20-L39

**Comment by njordsir** [comment]
@CyberZHG  Oh sweet! Will check this out. Going through the paper for BERT cleared my masking queries.
I meanwhile got the job done with the official tensorflow-hub module.

**Comment by BerenLuthien** [comment]
Thanks. The MaskedGlobalMaxPool1D itself works well in the demo you gave, but it looks it does not fit if we add a classification layer (such as Dense) on top of it:
This code gives error:
#
model = load_trained_model_from_checkpoint('bert_config.json', 'bert_model.ckpt') 
def get_custermized_model(model):
    pool_layer = MaskedGlobalMaxPool1D(name='Pooling')(model.output) 
    x = pool_layer
    x = Dense(units=1, activation='sigmoid')(x)
    print(model.inputs[0])    
    custermized_model = Model(inputs=model.inputs,  outputs=x)
    custermized_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
    return custermized_model
custermized_model = get_custermized_model(model=model)
history = custermized_model.fit(x=X_train, y=np.array(train_labels), epochs=3, validation_split=0.1)

>>
InvalidArgumentError: Incompatible shapes: [32] vs. [32,512]
	 [[{{node metrics_4/acc/mul}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics_4/acc/Mean, metrics_4/acc/Cast_1)]]
	 [[{{node metrics_4/acc/Mean_2/_1745}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4979_metrics_4/acc/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


Would you help 
- add a Dense layer on top of "MaskedGlobalMaxPool1D" and try how it works ? Thanks

**Comment by CyberZHG** [comment]
I forgot to return a `None` mask in `MaskedGlobalMaxPool1D `. I've fixed it and made a release.

**Comment by weizhenzhao** [comment]
@CyberZHG 
Hi cyberzhg

I notice in the code above
`
(1) model = load_trained_model_from_checkpoint(config_path, checkpoint_path) 


(2) model = load_trained_model_from_checkpoint(config_path, checkpoint_path, training=True, seq_len=seq_len)

`
if I build an classifier with bilstm on top of that ,
which means finetune?

Thanks
weiizhen
