### ISSUE TITLE
error on codec call, no file found

### ISSUE THREAD

**Issue by troy109** [CyberZHG/keras-bert#194]
Hello,

I am trying to run the codec call below but I am getting and error that the file is not found.

Also, isn't the codec call deprecated?

Also, I am not sure that the extract embeddings section of this code is supposed to do.  Is it writing the results?

**Describe the Bug**
```
Traceback (most recent call last):
  File "/home/troy/PycharmProjects/BERTPARSE/BERT-CODE/BERT_MIL.py", line 297, in <module>
    with codecs.open('xxx.txt', 'r', 'utf8') as reader:
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'xxx.txt'
```
**Version Info**

* [ ] I'm using the latest version

**Minimal Codes To Reproduce**

```python

with codecs.open('xxx.txt', 'r', 'utf8') as reader:
    texts = map(lambda x: x.strip(), reader)
    embeddings = extract_embeddings(model_path, texts)
```

**Comment by CyberZHG** [comment]
You should replace `xxx.txt` to the name of your own file.
