### ISSUE TITLE
Which version of keras-bert should I download? keras:2.2.4 tf:1.12.0

### ISSUE THREAD

**Issue by AliveHH** [CyberZHG/keras-bert#196]
when I pip install keras-bert, keras was automatically upgraded to 2.4.3, which does not match tf 1.12.0.
So, which version of keras-bert should I download?
thx~~~~

**Comment by CyberZHG** [comment]
See #193. Just use `0.84.0` and add `keras==2.2.4` to your pip command or requirement file.
