### ISSUE TITLE
SQuAD

### ISSUE THREAD

**Issue by D0cBrown** [CyberZHG/keras-bert#2]
Hi,
is it possible to apply the fine tuning of the original BERT model on SQuAD dataset as in the paper?

**Comment by CyberZHG** [comment]
Actually, the whole model (with MLM and NSP outputs) could be loaded from a checkpoint. Missing tokens and whether it is the next sentence could be predicted correctly in the small [demo](https://github.com/CyberZHG/keras-bert/blob/master/demo/load_model/load_and_predict.py) if you load the pre-trained Chinese model.  Although I think it's possible to do fine tuning, I'm not interested in reproducing the results.
