### ISSUE TITLE
single sentence classifier

### ISSUE THREAD

**Issue by BerenLuthien** [CyberZHG/keras-bert#21]
Does it support single sentence classifier (not pair-sentence) ?
Such as SST (http://nlp.stanford.edu/~socherr/stanfordSentimentTreebank.zip) or Cola dataset (https://nyu-mll.github.io/CoLA/), described in original BERT paper https://arxiv.org/pdf/1810.04805.pdf Section 4.1 GLUE dataset

If yes, what data format it should be ?
Can we simply input [sentence , padding_zeros] as a pair and get reasonable training ?

**Comment by CyberZHG** [comment]
I think the input could be [`'[CLS]'`, sentences, `'[SEP]'` `'[SEP]'`, 0, 0, 0, ...]

**Comment by BerenLuthien** [comment]
PS: if you wish to build your own classifier on top of BERT, and may have out-of-vocabulary (OOV) issue, refer to #22

**Comment by BerenLuthien** [comment]
Hi, adding [CLS] gives this trouble:

- following OOV (out of vocab) #22, if using "the tokenizer in the official repo " then [CLS] is broken into several parts, e.g.,
'[CLS] explanation why the edits made' -->
Out:
```
[u'[',
 u'cl',
 u'##s',
 u']',
 u'explanation',
 u'why',
 u'the',
 u'edit',
 u'##s',
 u'made']
```
**[CLS] is basically broken into several parts. 
Note we were trying to get the embedding of [CLS] and add some Dense (full connection) layer on top of it to do single-sentence-classification.**


On the other side, if using the customized tokenizer in #19  like 
keras-bert/demo/load_model/load_and_pool.py
Lines 20 to 39
There is OOV problem (#22 )


Thanks

**Comment by CyberZHG** [comment]
`[CLS]` and `[SEP]` shouldn't be concatenated to the text to be tokenized.
