### ISSUE TITLE
AttributeError: module 'keras' has no attribute 'applications'

### ISSUE THREAD

**Issue by vngrv** [CyberZHG/keras-bert#220]
I got this error via latest install for pip. This error a got after this: 
`from keras_bert.loader import load_trained_model_from_checkpoint`

Stacktrace:
`/usr/local/lib/python3.7/dist-packages/keras_bert/backend.py in <module>()
     18 utils = keras.utils
     19 activations = keras.activations
---> 20 applications = keras.applications
     21 backend = keras.backend
     22 datasets = keras.datasets

AttributeError: module 'keras' has no attribute 'applications'`

Okay. I had seen `https://github.com/CyberZHG/keras-bert/blob/master/keras_bert/backend.py` and i don't find call of application. Keras don't have applications method but tf.keras already have.
What i doing wrong?

**Comment by CyberZHG** [comment]
This may due to the update of tensorflow (2.5.0). Please try `keras-bert==0.87.0`.

**Comment by vngrv** [comment]
> This may due to the update of tensorflow (2.5.0). Please try `keras-bert==0.87.0`.

Already. Pip don't find this version. I guess don't find because test failed. I use pip install via link and than python gives me error for failed test before build package on my host.

**Comment by CyberZHG** [comment]
I don't think pip will/should run the tests before installing the package. It will decay a little time if you are using a mirror. `keras-bert==0.88.0` fixed the test cases.

**Comment by mtchibozo** [comment]
Set the environment variable `TF_KERAS=1` to force keras-bert to use tf.keras instead of keras.
`os.environ["TF_KERAS"]="1"`
