### ISSUE TITLE
How to get encoded sentence vector

### ISSUE THREAD

**Issue by aurora314156** [CyberZHG/keras-bert#26]
Hello, Sir

Thank you for implementation Keras version BERT.

Is there any way to get an encoded sentence vector?

I have a sentence like: 

The Top 25 Songs That Matter Right Now

And I want to get encoded sentence vector after putting this sentence to BERT.

Thx again.

**Comment by CyberZHG** [comment]
See #7 and #19.

**Comment by aurora314156** [comment]
Hi,

I put some English words into a sentence encoding, But get KerError.

Example : [ '[CLS]', 'I', 'can't', '[SEP]' ] etc.

Is there any solution for this situation?
