### ISSUE TITLE
batch prediction ?

### ISSUE THREAD

**Issue by BerenLuthien** [CyberZHG/keras-bert#27]
how to feed a batch of data to the model ? 

```
model.input_shape
[(None, 512), (None, 512)]
```
,

When I was trying to feed the model with a batch of data, such as **data shape = [64, 2, 512]** it gives
"ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays ..."

,
I was using something like this:
```
from keras.layers import Lambda
import keras.backend as K 
def mean(x):
    return K.mean(x, axis=1, keepdims=False)
###
inputs, embeds = get_model(
    token_num=len(token_dict),
    head_num=12,
    transformer_num=12,
    embed_dim=768,
    feed_forward_dim=100,
    seq_len=512,
    pos_num=512,
    dropout_rate=0.05,
    training = False,
)
####
avg_embeds = Lambda(mean)(embeds)
pred = Dense(1, activation="sigmoid")(avg_embeds)
model = Model(inputs=inputs, outputs=pred)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
```
Thanks

**Comment by CyberZHG** [comment]
You need to pass a list of two numpy arrays of size `[64, 512]`.
