### ISSUE TITLE
Use BERT to compute sentence similarity

### ISSUE THREAD

**Issue by rameshjesswani** [CyberZHG/keras-bert#28]
I want to compute similarity between two sentences (```sentA and sentB```). 
I have encoded each sentence using script i.e. [load_and_extract.py](https://github.com/CyberZHG/keras-bert/blob/master/demo/load_model/load_and_extract.py). so now embedding matrix of ```sentA``` and ```sentB``` has shape ```(1,512,768)```. After that i am thinking to add fully connected layer to compute the similarity between two sentences.

Note: I am using base model (with 12 hidden layers)

Question: Is this right approach to use BERT for sentence similarity? Furthermore, I have also seen some people are using ```MaskedGlobalMaxPool1D``` after hidden layers to encode the sentences. Do I have to take embeddings after applying ```MaskedGlobalMaxPool1D```? Why there is need of ```MaskedGlobalMaxPool1D``` ? 

Thanks in advance.

**Comment by CyberZHG** [comment]
See #7 and #19.

**Comment by ljch2018** [comment]
Do you solve this problem now ? Thanks.

**Comment by yonatanbitton** [comment]
I'll be very glad to know how to do it. 

I've seen:
https://github.com/CyberZHG/keras-bert/issues/7
https://github.com/CyberZHG/keras-bert/issues/19

And implemented the 'demo' in 'issues/19' but I'm still unable to calculate the sentence similarity.

Does someone know the answer?

**Comment by rameshjesswani** [comment]
you can use [bert-as-service](https://github.com/hanxiao/bert-as-service) and compute the sentence similarity easily. It also gives you elmo like embeddings.

**Comment by yonatanbitton** [comment]
I know bert-as-a-service and I've asked how to encode works:
https://github.com/hanxiao/bert-as-service/issues/384

I would like to know how to extract the 'sentence embeddings' myself.
I'll check the ELMo like embeddings as well. Thanks.
