### ISSUE TITLE
How to apply BERT to a cloze-style QA task?

### ISSUE THREAD

**Issue by Deep1994** [CyberZHG/keras-bert#3]
Great job! Can I apply it to the cloze-style QA task, which is to predict the words that are masked according to the context. How should the input of the model be organized?

For example:

The dataset looks like:

From Monday to Friday most people are busy working or studying, but in the evenings and weekends they are free and  _  themselves.
And there are four candidate answers : 

options": [
        [
            "love", 
            "work", 
            "enjoy", 
            "play"
        ]

Apparently the correct answer is "enjoy"， How can I organize the input so that BERT can predict the missing word given the context? Thank you for your excellent code!

**Comment by CyberZHG** [comment]
https://github.com/CyberZHG/keras-bert/blob/master/demo/load_model/load_and_predict.py#L15,L30

If you just need the prediction results, you can replace the blank area with variable length `[MASK]`s in `token_input` based on your candidates and set the corresponding locations to `1` in `mask_input`. You could find the probabilities of your candidates in the output results.
