### ISSUE TITLE
MaskConv1D

### ISSUE THREAD

**Issue by BerenLuthien** [CyberZHG/keras-bert#31]
**Is your feature request related to a problem? Please describe.**
Error when adding a Conv1D layer on top of the BERT embeddings, complaining about "mask".

**Describe the solution you'd like**
Can you make a class for MaskConv1D layer, similar as MaskGlobalMaxPooling ? 

**Describe alternatives you've considered**
PR

**Additional context**
N/A

**Comment by CyberZHG** [comment]
https://github.com/CyberZHG/keras-bert/blob/549da47026226d569afea368cb66d7cb5d825e32/keras_bert/layers/conv.py#L5-L18
