### ISSUE TITLE
Single-Sentence Input?

### ISSUE THREAD

**Issue by bfan1256** [CyberZHG/keras-bert#33]
A little new to the BERT model, but it seems that in your code, you have a `gen_batch_inputs()`  function that only allows for sentence pairing to be passed through. How would you implement a dataset for single-sentence encoding or classification?

**Comment by bfan1256** [comment]
Nevermind, I see that #21 provides a beneficial solution. I suspect that a single-sentence input should be implemented however as it is a critical and important task.

**Comment by BerenLuthien** [comment]
Also #22 maybe useful to you @bfan1256
