### ISSUE TITLE
Padding zeros

### ISSUE THREAD

**Issue by sangwoo3** [CyberZHG/keras-bert#36]
Hi,

Thank you for your keras BERT code. I'd like to report a padding issue.

The rest of segment ids should be padded with zeros not ones.
```python
segments += [1] * (max_len - len(segments))
==>
segments += [0] * (max_len - len(segments))
```
code from tokenizer.py [link](https://github.com/CyberZHG/keras-bert/blob/2df9a66ac40d1017792b1c93f34e47e214726d7d/keras_bert/tokenizer.py#L38)

**Comment by CyberZHG** [comment]
The rest could be any number.

**Comment by CyberZHG** [comment]
See also #14.

**Comment by sangwoo3** [comment]
Thanks for the information.
