### ISSUE TITLE
The sepration of this repo make it much harder to read the code now.

### ISSUE THREAD

**Issue by huangxiangzhou** [CyberZHG/keras-bert#4]
Awesome work!
However I have noticed that you have split this repo into 5 or 6 diff repos recently, which make the entire src much harder to follow now.
I think it`s better to keep all your customize code in a same repo, just a suggestion.

**Comment by CyberZHG** [comment]
The separation is for convenience and faster unit testing, and most importantly, they DO NOT belong to the BERT paper. Maybe you need an IDE to jump to the definitions.

**Comment by LCorleone** [comment]
+1
