### ISSUE TITLE
Explanation of parameter max_len in tokenizer.encode ？

### ISSUE THREAD

**Issue by Kiris-tingna** [CyberZHG/keras-bert#40]
It seems that this parameter should be capable with the pretrained BERT model , but where to find the setting in donwleded bert_config?

**Comment by CyberZHG** [comment]
https://github.com/CyberZHG/keras-bert/blob/5380fa45adf3b1b38944ae8204d973a441c4b381/demo/load_model/load_and_extract.py#L9

**Comment by houchangtao** [comment]
In the load and extract demo, which model you are loading? I tried the model: uncased_L-12_H-768_A-12 but get a different result as you got.

**Comment by CyberZHG** [comment]
@houchangtao  `chinese_L-12_H-768_A-12`

**Comment by houchangtao** [comment]
@CyberZHG  Thanks!
