### ISSUE TITLE
Tokenization on Cased Model

### ISSUE THREAD

**Issue by michaelnation26** [CyberZHG/keras-bert#41]
**Is your feature request related to a problem? Please describe.**
On the original BERT implementation from Google, the tokenizer does not perform normalization (lower casing, accent stripping, or Unicode normalization) on the input when using a cased model. e.g. Multilingual Cased

**Describe the solution you'd like**
In the Tokenization class, prevent normalization on the input when the model is cased.

**Additional context**
Lines 71 - 73 in tokenizer.py

**Comment by CyberZHG** [comment]
Thanks. Now you can set `cased` to `True` to skip normalization and lower casing.

https://github.com/CyberZHG/keras-bert/blob/17b41d5bd8afe6cf38c1f98c2401026e674cce71/keras_bert/tokenizer.py#L13

**Comment by michaelnation26** [comment]
Looks great, thank you!
