### ISSUE TITLE
ImportError : cannot import name 'Tokenizer'

### ISSUE THREAD

**Issue by heany** [CyberZHG/keras-bert#49]
**Describe the Bug**

when I use the keras_bert to execute the demo [https://github.com/CyberZHG/keras-bert/blob/master/demo/load_model/load_and_extract.py](url), it gives me a error about the import the `Tokenizer`.  The detailed  description is shown as follow:

And What is the cause of this problem?
thanks

**Minimal Codes To Reproduce**

```python
import keras_bert

from keras_bert import load_trained_model_from_checkpoint
from keras_bert import Tokenizer

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-27-cdcfeee15447> in <module>()
      1 from keras_bert import load_trained_model_from_checkpoint
----> 2 from keras_bert import Tokenizer

ImportError: cannot import name 'Tokenizer'

```
![image](https://user-images.githubusercontent.com/28182428/56562255-998e6500-65db-11e9-948e-57a132315873.png)

**Comment by CyberZHG** [comment]
I guess you are using an outdated version of the package.

```bash
pip install --upgrade keras-bert
```

**Comment by heany** [comment]
The package of keras-bert is the newest. The problem is solved when I  re-install the keras-bert.
Thanks!
