### ISSUE TITLE
What does token_num parameter in get_model function mean?

### ISSUE THREAD

**Issue by kbulutozler** [CyberZHG/keras-bert#51]

**Comment by CyberZHG** [comment]
The size of your dictionary / The input dimension of the embedding

**Comment by kbulutozler** [comment]
I am getting memory errors (used several GPUs with at least 12 gb ram) even for a small size (7k) of dictionary. Considering the real dictionary must consist 100k tokens, there is something wrong. I opened an issue at Keras repo, I will be really happy if you can take a look since it is based on your code. 
link: https://github.com/keras-team/keras/issues/12755

**Comment by CyberZHG** [comment]
I think you misunderstood `steps_per_epoch`. If you are using a generator, then the batch size is controlled only by the generator itself. Setting `steps_per_epoch` means there are `batch_size` x `steps_per_epoch`samples in one epoch.

**Comment by kbulutozler** [comment]
But don't we set number of sequences/samples? Doesn't this allow us control batch size by changing `steps_per_epoch ` ?

**Comment by CyberZHG** [comment]
There is no way to modify your generator "intelligently" since you may need operators like padding.

**Comment by kbulutozler** [comment]
Okay. What do you suggest about deciding the value of `steps_per_epoch `?
