### ISSUE TITLE
ValueError: Tensor Tensor("Encoder-12-FeedForward-Norm/add_1:0", shape=(?, 32, 768), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by yongzhuo** [CyberZHG/keras-bert#54]
my code is :
                      model_bert = keras_bert.load_trained_model_from_checkpoint(......)
                      model_bert_real = Model(inputs=model_bert .inputs, outputs=model_bert .output)
                      bert_encode = model_bert_real.predict(batch_size=1, x=input_sample)

when I call this program  with django, error happend,

ValueError: Tensor Tensor("Encoder-12-FeedForward-Norm/add_1:0", shape=(?, 32, 768), dtype=float32) is not an element of this graph.

how could i slove it?

**Comment by mathxin** [comment]
> `bert.output`?

Please check the issue[#53](https://github.com/CyberZHG/keras-bert/issues/53#issue-439155762).
I've been puzzled for a long time.

**Comment by yongzhuo** [comment]
ok, thanks
