### ISSUE TITLE
Example for concatenated feature extraction

### ISSUE THREAD

**Issue by naibaf1991** [CyberZHG/keras-bert#55]
Dear all,

the original BERT paper describes a _feature-based approach_, which uses a pretrained model and then **concatenates the last four hidden layers**, on which they built 2 LSTM layers and then a classifier. 

Could you provide us with an **_example on how to perform the extraction and concatenation of the last four hidden layers_**? 
According to the paper, this performs almost as good as finetuning all layers and would therefore be very useful in combination with this excellent package! 

Thank you very much in advance!

**Comment by CyberZHG** [comment]
Done. Use `output_layer_num`:

https://github.com/CyberZHG/keras-bert/blob/2a4a981b9fda45d385bc98656c9dc494bb05d36e/tests/test_loader.py#L33
