### ISSUE TITLE
how can i change the max_len??

### ISSUE THREAD

**Issue by Lx1010** [CyberZHG/keras-bert#59]
**Describe the Bug**

**Version Info**

* [x] I'm using the latest version

**Minimal Codes To Reproduce**

```python
import keras_bert

pass
```

**Comment by Lx1010** [comment]
What should I do when my sentence length is greater than 512 bytes

**Comment by FrankLicm** [comment]
> What should I do when my sentence length is greater than 512 bytes

see https://github.com/google-research/bert/issues/66

**Comment by Lx1010** [comment]
> 
> 
> > What should I do when my sentence length is greater than 512 bytes
> 
> see [google-research/bert#66](https://github.com/google-research/bert/issues/66)

Okay got it, that makes sense. Thanks for your help!
