### ISSUE TITLE
How to apply BERT to a custom classification model?

### ISSUE THREAD

**Issue by Scarlettg** [CyberZHG/keras-bert#6]
Let's say I'm trying to load a pretrained BERT model from a checkpoint, add layers after it and build the model with Model.compile():

What does the input have to look like if BERT is the first "layer"? Would be nice to have a simple example.

**Comment by CyberZHG** [comment]
See [extract demo](https://github.com/CyberZHG/keras-bert/blob/6083bb07271a69c7943ed011cad463ab31f649ef/demo/load_model/load_and_extract.py#L17-L24).

There are two inputs with shape `(batch_size, 512)`. For token input you should load `vocab.txt` just like the demo, then map words to indices. The segment input is a zero array if you don't need to compare two parts of the text input.
