### ISSUE TITLE
position embedding and masking?

### ISSUE THREAD

**Issue by LCorleone** [CyberZHG/keras-bert#72]
My input is sentence pairs, like [CLS] the dog is clever [SEP] he is cool [SEP]
I look into your code and still did not figure out how to set up the input for BERT.
It seems to have two input, token input and segment input.
For example, in my case above, the input token is 
[CLS] x x x x [SEP] x x x [SEP]    the segment token is
0 0 0 0 0 0 1 1 1 1 ? is this right?
and two questions 1. where is the position token? 2. the padding is also 0, is there any conflict?
Thanks!

**Comment by CyberZHG** [comment]
> For example, in my case above, the input token is

Right

> 1. where is the position token?

The position tokens are fixed and generated inside the model. Therefore you don't need to generate the tokens yourself.

> 2. the padding is also 0, is there any conflict?

No. Masks are generated from input tokens.

**Comment by LCorleone** [comment]
@CyberZHG many thanks for your quick reply!
