### ISSUE TITLE
get some error with the new keras-bert

### ISSUE THREAD

**Issue by Lx1010** [CyberZHG/keras-bert#73]
hello，i have loaded this project one month ago，it works. but today i restart it,it was fail.
i have reload this project and uninstall the old keras-bert and reinstall
and i get this error.could you help me how to deal with it?
thanks!
**Describe the Bug**
AttributeError: module 'tensorflow.python.training.training' has no attribute 'load_variable'

**Comment by lu161513** [comment]
我也发生这个问题了，怎么解决的？
