### ISSUE TITLE
Out of Memory Issue

### ISSUE THREAD

**Issue by xiaoleihuang** [CyberZHG/keras-bert#75]
I have memory issues that can not fit the bert model on local desktop (one GPU of 11 G memory). The smallest bert model can not fit to the desktop GPU, is there a method lower down the memory cost? I have 16 batch size and the seq len is just 64.

**Comment by LHongchao** [comment]
I think, if you do not want to cut too much words and dimensions from the model, you can just allocate more space from your hard disk to the virtual RAM. This is feasible when you have a computer with SSD. HDD, altough OK, will cost too much time on I/O because of its low speed.
