### ISSUE TITLE
How to save fine tuned language model after a classification task

### ISSUE THREAD

**Issue by funqc** [CyberZHG/keras-bert#76]
I implemented a classification task according to the demo. I want to save the fine-tuned language model, not including the classification layer. what should I do？

**Comment by CyberZHG** [comment]
```python
outputs = model.get_layer('last-layer-name').output
model = Model(inputs=model.inputs, outputs=outputs)
model.save('path')
```

**Comment by xxxxxxxxy** [comment]
我训练了一个分类的模型，通过model.save('keras_bert.h5')保存了下来，但是在调用这个模型的时候：load_model('keras_bert.h5')出现了Unknown layer: TokenEmbedding的错误。训练过程中没有自定义Layer，请问这种情况下如何加载模型？

**Comment by CyberZHG** [comment]
> 我训练了一个分类的模型，通过model.save('keras_bert.h5')保存了下来，但是在调用这个模型的时候：load_model('keras_bert.h5')出现了Unknown layer: TokenEmbedding的错误。训练过程中没有自定义Layer，请问这种情况下如何加载模型？

```python
from keras_bert import get_custom_objects

load_model('keras_bert.h5', custom_objects=get_custom_objects())
```

**Comment by funqc** [comment]
谢谢，解决了我的问题

**Comment by tinkermachine** [comment]
> ```python
> outputs = model.get_layer('last-layer-name').output
> model = Model(inputs=model.inputs, outputs=outputs)
> model.save('path')
> ```

Do we need the first 2 lines? Can we not just do model.save('path') after the model has been already fit?
