### ISSUE TITLE
Multiple Inputs

### ISSUE THREAD

**Issue by xinsu626** [CyberZHG/keras-bert#80]
I was wondering if it is possible to use this library to build a model, which can have multiple inputs.

Like:

```
inputs1 = ...
inputs2 = ...
inputs1_embedded = bert_embedding()(inputs1)
inputs2_embedded = bert_embedding()(inputs2)
model_out1 = model()(inputs1_embedded)
model_out2 = model()(inputs2_embedded)
....
```

**Comment by CyberZHG** [comment]
`Model` is callable just like `Layer`s:

```python
import os
import keras
from keras_bert import load_trained_model_from_checkpoint

inputs_1 = [
    keras.layers.Input(shape=(16,), name='Input-Token-1'),
    keras.layers.Input(shape=(16,), name='Input-Segment-1'),
]
inputs_2 = [
    keras.layers.Input(shape=(16,), name='Input-Token-2'),
    keras.layers.Input(shape=(16,), name='Input-Segment-2'),
]

current_path = os.path.dirname(os.path.abspath(__file__))
config_path = os.path.join(current_path, 'test_checkpoint', 'config.json')
model_path = os.path.join(current_path, 'test_checkpoint', 'model.ckpt-20')
model = load_trained_model_from_checkpoint(
    config_path,
    model_path,
    training=False,
    trainable=['Encoder'],
)

outputs_1 = model(inputs_1)
outputs_2 = model(inputs_2)
model = keras.models.Model(inputs=inputs_1 + inputs_2, outputs=[outputs_1, outputs_2])
model.summary()
```

**Comment by ericpts** [comment]
Also it seems that the `Segment` input should always be 0, so I myself do this instead:

```python
    bert_model = keras_bert.load_trained_model_from_checkpoint(
        str(config_path),
        str(checkpoint_path),
        training=True,
        trainable=True,
        seq_len=constants.MAX_SEQUENCE_LENGTH
    )
    (indices, always_zero) = bert_model.inputs[:2]
    dense = bert_model.get_layer('NSP-Dense').output
    bert_model = keras.models.Model(
        inputs=(indices, always_zero),
        outputs=dense,
        name='bert_embeddings'
    )

    inputs = indices
    X = bert_model(
        [inputs, tf.zeros_like(inputs)]
    )

    X = keras.layers.Dense(1, activation='sigmoid')(X)
```

**Comment by xinsu626** [comment]
@CyberZHG Thank you for your reply. When I was trying to run your code, I got a value error like below. Do I also need to prepare the masked input for loaded trained model?

```
ValueError: Layer model_1 expects 3 inputs, but it received 2 input tensors. Input received: [<tf.Tensor 'Input-Token-1:0' shape=(?, 128) dtype=float32>, <tf.Tensor 'Input-Segment-1:0' shape=(?, 128) dtype=float32>]
```

**Comment by CyberZHG** [comment]
> For the `training` parameter in `load_trained_model_from_checkpoint` function, does it simply means no masked language layer after encoders output if I set the parameter to `True` ?

No masked language layer if it is `False`.

> When I was reading your Chinese README, it says "如果不想再训练嵌入层，可以传入`trainable=['Encoder']`来只对编码层进行调整". Does this means if set trainable to [encoder] I am not fine tuning the bert's embedding layers?

Yes.

**Comment by xinsu626** [comment]
@CyberZHG 

Thanks a lot for your prompt replies. The reason I would like to try multiple inputs is to use the Bert model on a long sequence. But I found that when I had too many inputs, I still faced memory limitations.

I also tried TimeDistributed wrapper to wrap the bert model like `TimeDistributed(bert)([token_input, segment_input])`, but it was not working. Currently, I am using part of your source code(transformer and bert) to build a time distributed model.  Do you have any suggestions for long sequence?
