### ISSUE TITLE
AdamWarmup cannot be serialized in SavedModel

### ISSUE THREAD

**Issue by mfojtak** [CyberZHG/keras-bert#84]
**Describe the Bug**

The following warning is thrown when trying to export the model using
```python
tf.keras.experimental.export_saved_model(model, 'saved_model/', custom_objects = bert.get_custom_objects())
```

```
This model was compiled with a Keras optimizer (<keras_bert.optimizers.warmup.AdamWarmup object at 0x7f8eedb0ada0>) but is being saved in TensorFlow format with `save_weights`. The model's weights will be saved, but unlike with TensorFlow optimizers in the TensorFlow format the optimizer's state will not be saved.

Model was compiled with an optimizer, but the optimizer is not from `tf.train` (e.g. `tf.train.AdagradOptimizer`). Only the serving graph was exported. The train and evaluate graphs were not added to the SavedModel
```

**Version Info**

* [ ] I'm using the latest version

**Minimal Codes To Reproduce**

```python
tf.keras.experimental.export_saved_model(model, 'saved_model/', custom_objects = bert.get_custom_objects())
```

**Comment by CyberZHG** [comment]
Why don't you use `model.save('xxx')`?

Besides, I don't think it's a big problem since the optimizer will run in minimal lr (default is 0) if the states are loaded. You'll either do prediction with the model without the optimizer or rebuild the optimizer for further training.

**Comment by mfojtak** [comment]
I am using export_saved_model to be able to use the model in tensorflow serving.
It won't even export the training and evaluate graphs if the AdamW is there.

**Comment by CyberZHG** [comment]
I don't think you need the training and evaluation graphs for serving. However, you can re-compile the model at any time:

```python
model.compile(optimizer=tf.train.AdamOptimizer(), loss='sparse_categorical_crossentropy')
```
