### ISSUE TITLE
Tensorflow 2 Error

### ISSUE THREAD

**Issue by tinkermachine** [CyberZHG/keras-bert#90]
I am getting a A**ttributeError: module 'tensorflow' has no attribute 'placeholder'** on tensorflow 2.0-gpu

Looks like its coming from the backend.py file. 

Is the code TF2.0 compliant now? I was under the impression it was but maybe I am wrong

**Comment by CyberZHG** [comment]
It's documented in the Chinese version of README. Add `TF_KERAS=1` to your environment variables.
