### ISSUE TITLE
Has anyone managed to integrate this with the Tf.data dataset functions?

### ISSUE THREAD

**Issue by tinkermachine** [CyberZHG/keras-bert#99]
Have anyone been able to use this repo with the from_tensor_slices function function from the Tf.data modeule? I keep ending up with a ValueError..

`ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [<tf.Tensor 'IteratorGetNext:0' shape=(?, 2, 128) dtype=int32>]...`

**Comment by veqtor** [comment]
You need to also pass segments...
Your inputs look a bit weird, what exactly is the 2,128 array?

Do you have your own training function?

If you could post a bit more code that would be helpful
